"""Ajout de la colonne tontine_cycle_id à la table transaction

Revision ID: 4963216004fa
Revises: 
Create Date: 2025-06-03 21:44:27.949176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4963216004fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tontine_cycle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transaction_tontine_cycle_id',  # <-- nom explicite
            'tontine_cycle',
            ['tontine_cycle_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_tontine_cycle_id', type_='foreignkey')
        batch_op.drop_column('tontine_cycle_id')
    # ### end Alembic commands ###
