"""Add joined_at column to user_tontine

Revision ID: 597a2303f830
Revises: 3694222fe970
Create Date: 2025-06-14 01:55:37.167503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597a2303f830'
down_revision = '3694222fe970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tontine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tontine', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###
