"""Add is_private to tontine

Revision ID: ffe48122bdce
Revises: 4963216004fa
Create Date: 2025-06-13 15:25:10.124367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe48122bdce'
down_revision = '4963216004fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tontine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('amount_per_member',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('max_members',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_tontine', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tontine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('tontine', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_members',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('amount_per_member',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
